---

- name: kiosk role
  hosts: kiosk
  become: true
  tasks:
    - name: Kiosk groups
      group:
        name: "{{ item }}"
      loop: "{{ user_groups }}"

    - name: Add the user 'dlrgwgt'
      user:
        name: dlrgwgt
        comment: DLRG Weingarten Wache
        groups:
          - kiosk
          - dlrgwgt
