#!/usr/bin/env ansible-playbook
---
- name: site role
  hosts: all
  become: true
  tasks:
    #- name: set hostname
    #  hostname: "{{ hostname }}"
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: true
        cache_valid_time: 3600
    - name: "Basic dependencies"
      apt:
        name:
          - vim
          - tmux
          - git
          - mosquitto-clients
          - mosquitto
          - tinc
          - mosh
    - name: Add groups
      group:
        name: "envsensor"
    - name: Add groups
      group:
        name: "sshusers"
    - name: Add groups
      group:
        name: "admin"
    - name: Add groups
      group:
        name: "webcam"
    - name: Add the user 'envsensor'
      user:
        name: envsensor
        comment: Sensor
        groups:
          - envsensor
          - gpio
        system: true
    - name: Webcam
      user:
        name: webcam
        group: webcam
        system: true
    - name: admin
      user:
        name: admin
        groups: "{{ admin_groups }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: Add the user 'toke'
      user:
        name: toke
        comment: Thomas Kerpe
        groups: "{{ admin_groups }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    # - name: Remove the user 'pi'
    # user:
    #   name: pi
    #   state: absent

    - name: Set authorized key, removing all the authorized key already set
      authorized_key:
        user: toke
        key: '{{ item }}'
        state: present
      with_file:
        - public_keys/toke_bluesky.pub

    - name: Set authorized key, removing all the authorized key already set
      authorized_key:
        user: pi
        key: '{{ item }}'
        state: present
      with_file:
        - public_keys/toke_bluesky.pub

  roles:
    - role: whiskerlabs.watchdog
      watchdog_max_load_5: "10"
      #watchdog_interfaces: [eth0]
      #watchdog_interval: "10"
#    - mqtt:
#        topic: 'service/ansible/{{ ansible_hostname }}'
#        payload: 'Hello at {{ ansible_date_time.iso8601 }}'
#        qos: 0
#        retain: false
#        client_id: ans001
#      delegate_to: localhost
- import_playbook: vpn.yml
- import_playbook: kiosk.yml
